### ISSUE TITLE
Comparison with two other addins

### ISSUE THREAD

**Issue by maelle** [richarddmorey/tweetRcode#1]
Great work! 

I have one suggestion: comparing your cool addin to what [`codefinch`](https://github.com/ropenscilabs/codefinch) by @seankross and the Twitter RANT addin of [`hrbraddins`](https://github.com/hrbrmstr/hrbraddins) by @hrbrmstr do (in the README?). I imagine one point is that yours does it all. 😉 ?)

**Comment by richarddmorey** [comment]
Thanks, I added these to the README.
